name: staff_identity_app
description: The digital gatepass app for staff.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- Staff App Specific Dependencies ---
  # To save the Staff ID permanently on the phone
  shared_preferences: ^2.2.2

  # To generate the QR Code
  qr_flutter: ^4.1.0

  # To set screen brightness to 100% when showing QR
  screen_brightness: ^0.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
